### ISSUE TITLE
Error on triggering completions.

### ISSUE THREAD

**Issue by captain0xff** [python-lsp/python-lsp-server#124]
OS: Windows 10
Editor: Sublime 4121

Steps to reproduce:-
1. Create a document:-
```import pygame as pg```
```pg.display.set```
2. Trigger completion after the last character and choose the ```set_mode``` function.

The autocompletion is completed but the cursor comes after the closing bracket instead of coming between the opening and closing ones. And I get the following errors:-
```
LSP-pylsp: 2021-11-26 00:05:04,469 India Standard Time - ERROR - pylsp_jsonrpc.endpoint - Failed to handle request 12
LSP-pylsp: Traceback (most recent call last):
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp_jsonrpc\endpoint.py", line 116, in consume
LSP-pylsp:     self._handle_request(message['id'], message['method'], message.get('params'))
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp_jsonrpc\endpoint.py", line 185, in _handle_request
LSP-pylsp:     handler_result = handler(params)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp_jsonrpc\dispatchers.py", line 25, in handler
LSP-pylsp:     return method(**(params or {}))
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp\python_lsp.py", line 318, in m_completion_item__resolve
LSP-pylsp:     return self.completion_item_resolve(completionItem)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp\python_lsp.py", line 269, in completion_item_resolve
LSP-pylsp:     return self._hook('pylsp_completion_item_resolve', doc_uri, completion_item=completion_item)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp\python_lsp.py", line 156, in _hook
LSP-pylsp:     return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
LSP-pylsp:     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
LSP-pylsp:     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_manager.py", line 327, in traced_hookexec
LSP-pylsp:     return outcome.get_result()
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_result.py", line 60, in get_result
LSP-pylsp:     raise ex[1].with_traceback(ex[2])
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_result.py", line 33, in from_call
LSP-pylsp:     result = func()
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_manager.py", line 324, in <lambda>
LSP-pylsp:     lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
LSP-pylsp:     return outcome.get_result()
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_result.py", line 60, in get_result
LSP-pylsp:     raise ex[1].with_traceback(ex[2])
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
LSP-pylsp:     res = hook_impl.function(*args)
LSP-pylsp:   File "C:\Users\debja\AppData\Local\Sublime Text\Package Storage\LSP-pylsp\lib\site-packages\pylsp\plugins\rope_completion.py", line 86, in pylsp_completion_item_resolve
LSP-pylsp:     completion, data = document.shared_data['LAST_ROPE_COMPLETIONS'].get(completion_item['label'])
LSP-pylsp: TypeError: cannot unpack non-iterable NoneType object
```
I have asked in the pylsp github and they asked to ask here.
Thank You.

**Comment by captain0xff** [comment]
Duplicate of this https://github.com/python-lsp/python-lsp-server/issues/123. They already created an issue just 5 minutes before.
