### ISSUE TITLE
Crash on windows in network shares

### ISSUE THREAD

**Issue by gamag** [python-lsp/python-lsp-server#160]
Hi, 

First of all, thank you for your work on this very useful piece of software!

I'm running into a crash using the lsp server v1.2.4 on windows in a network share via jupyter lab plugin:

```
ERROR - pylsp_jsonrpc.endpoint - Failed to handle request 25
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp_jsonrpc\endpoint.py", line 116, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp_jsonrpc\endpoint.py", line 185, in _handle_request
    handler_result = handler(params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp_jsonrpc\dispatchers.py", line 25, in handler
    return method(**(params or {}))
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\python_lsp.py", line 356, in m_text_document__document_highlight
    return self.highlight(textDocument['uri'], position)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\python_lsp.py", line 287, in highlight
    return flatten(self._hook('pylsp_document_highlight', doc_uri, position=position)) or None
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\python_lsp.py", line 154, in _hook
    doc = workspace.get_document(doc_uri) if doc_uri else None
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\workspace.py", line 86, in get_document
    return self._docs.get(doc_uri) or self._create_document(doc_uri)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\workspace.py", line 127, in _create_document
    extra_sys_path=self.source_roots(path),
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\workspace.py", line 117, in source_roots
    files = _utils.find_parents(self._root_path, document_path, ['setup.py', 'pyproject.toml']) or []
  File "C:\ProgramData\Anaconda3\lib\site-packages\pylsp\_utils.py", line 68, in find_parents
    dirs = [root] + os.path.relpath(os.path.dirname(path), root).split(os.path.sep)
  File "C:\ProgramData\Anaconda3\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'Z:', start on mount '\\\\windata.example.com\\dir'
````
`windata.example.com\dir` and `Z:` are the same drive.

The problem seems to be, that on windows different drives don't have a common parent directory, so python refuses to give a relpath, however in this case, there are two valid names for the drive.

There is a related python issue for this: https://bugs.python.org/issue40732 (closed as "not a bug")

A quick and easy solutions seems to be to just wrap the two arguments of the `relpath` call  (_utils.py:68)  in `os.path.realpath`.

**Comment by ccordoba12** [comment]
Hey @gamag, thanks for reporting. I don't understand very well what you mean by your fix, so please open a pull request for it.
