### ISSUE TITLE
some import-error on Ubuntu 20 x64

### ISSUE THREAD

**Issue by Alexey-T** [python-lsp/python-lsp-server#213]
Ubuntu 20 x64, Py 3.8.
I removed python-language-server (OLD) and installed new one

`pip install python-lsp-server`

Now I can run `pylsp` from terminal. it gives error!
```
user@PC:~$ pylsp
Traceback (most recent call last):
  File "/usr/local/bin/pylsp", line 5, in <module>
    from pylsp.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/pylsp/__main__.py", line 15, in <module>
    from .python_lsp import (PythonLSPServer, start_io_lang_server,
  File "/usr/local/lib/python3.8/dist-packages/pylsp/python_lsp.py", line 15, in <module>
    from .config import config
  File "/usr/local/lib/python3.8/dist-packages/pylsp/config/config.py", line 11, in <module>
    from pluggy._hooks import HookImpl
ModuleNotFoundError: No module named 'pluggy._hooks'
user@PC:~$ which pylsp
/usr/local/bin/pylsp
user@PC:~$ 
```

@veksha Maybe you know the reason

**Comment by Alexey-T** [comment]
```
pylsp --help
```
also gives the same error.

**Comment by Alexey-T** [comment]
installing `pluggy` dont help, why?
```
user@PC:~$ sudo pip install pluggy
[sudo] password for user: 
Requirement already satisfied: pluggy in /usr/local/lib/python3.8/dist-packages (1.0.0)
user@PC:~$ 
```

**Comment by veksha** [comment]
googling it for you
`pip install --upgrade pytest-metadata`
helps? :)

had no such error here on Windows

**Comment by Alexey-T** [comment]
I run this, it installed smthing, but still the same error..

**Comment by veksha** [comment]
sorry, `pytest-metadata` is not needed for your case.

**Comment by Alexey-T** [comment]
solved!!

```
user@PC:~$ pip uninstall pluggy
Found existing installation: pluggy 0.13.1
Uninstalling pluggy-0.13.1:
  Would remove:
    /home/user/.local/lib/python3.8/site-packages/pluggy-0.13.1.dist-info/*
    /home/user/.local/lib/python3.8/site-packages/pluggy/*
Proceed (y/n)? y
  Successfully uninstalled pluggy-0.13.1
user@PC:~$ sudo pip install pluggy
[sudo] password for user: 
Requirement already satisfied: pluggy in /usr/local/lib/python3.8/dist-packages (1.0.0)
```
