### ISSUE TITLE
Add support to `textDocument/semanticTokens/full` from lsp specification

### ISSUE THREAD

**Issue by Hebe970217** [python-lsp/python-lsp-server#271]
my log:
```
-> to backend request
Content-Length: 161

{"id":14,"jsonrpc":"2.0","method":"textDocument/semanticTokens/full","params":{"textDocument":{"uri":"file:///home/funning/PycharmProjects/testPython/main.py"}}}
2022-09-27 17:40:57,381 UTC - ERROR - pyls_jsonrpc.endpoint - Failed to handle request 14
Traceback (most recent call last):
  File "/home/funning/.local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 178, in _handle_request
    handler = self._dispatcher[method]
  File "/home/funning/.local/lib/python3.7/site-packages/pyls/python_ls.py", line 136, in __getitem__
    raise KeyError()
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/funning/.local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/funning/.local/lib/python3.7/site-packages/pyls_jsonrpc/endpoint.py", line 180, in _handle_request
    raise JsonRpcMethodNotFound.of(method)
pyls_jsonrpc.exceptions.JsonRpcMethodNotFound: Method Not Found: textDocument/semanticTokens/full

<-- front request result
Content-Length: 114
Content-Type: application/vscode-jsonrpc; charset=utf8

{"jsonrpc":"2.0","id":14,"error":{"code":-32601,"message":"Method Not Found: textDocument\/semanticTokens\/full"}}
```

I see that this option request can be traced back to last year. When can this function be supported or has the plan been started?
If there is no relevant plan, I would be happy to work for Pyls.

**Comment by ccordoba12** [comment]
No one is working on this.

**Comment by rchl** [comment]
You've already found the #103 issue. Why have you created a duplicate one?

**Comment by Hebe970217** [comment]
> You've already found the #103 issue. Why have you created a duplicate one?

I have seen that the time is too long, and there has been no relevant reply item, so I put forward a new one, and now I close it
