### ISSUE TITLE
pylsp_document_symbols raising TypeError from os.path.samefile

### ISSUE THREAD

**Issue by douglasdavis** [python-lsp/python-lsp-server#30]
It looks like https://github.com/python-lsp/python-lsp-server/blob/5a13db19fbecc25ea565eed1a16545450a6ccac8/pylsp/plugins/symbols.py#L41-L46 should perhaps look for a TypeError or check for `None`s before calling `samefile`? I'm making this guess passed on the following traceback:

```python-traceback
Traceback (most recent call last):
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py", line 116, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp_jsonrpc/endpoint.py", line 185, in _handle_request
    handler_result = handler(params)
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp_jsonrpc/dispatchers.py", line 25, in handler
    return method(**(params or {}))
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp/python_lsp.py", line 334, in m_text_document__document_symbol
    return self.document_symbols(textDocument['uri'])
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp/python_lsp.py", line 250, in document_symbols
    return flatten(self._hook('pylsp_document_symbols', doc_uri))
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp/python_lsp.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/manager.py", line 337, in traced_hookexec
    return outcome.get_result()
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/manager.py", line 335, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/ddavis/.pyenv/versions/3.9.5/envs/dask-dev/lib/python3.9/site-packages/pylsp/plugins/symbols.py", line 42, in pylsp_document_symbols
    docismodule = os.path.samefile(document.path, d.module_path)
  File "/Users/ddavis/.pyenv/versions/3.9.5/lib/python3.9/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by ccordoba12** [comment]
I think catching TypeError is better here because it'd cover the case in which `document.path`, `d.module_path` are both None.

Could you create a PR for it? Thanks!

**Comment by douglasdavis** [comment]
Sure! Just opened one.
