### ISSUE TITLE
Failed to load hook pylsp_document_symbols

### ISSUE THREAD

**Issue by eyalk11** [python-lsp/python-lsp-server#437]
```
[ERROR][2023-09-10 05:07:14] .../vim/lsp/rpc.lua:734	"rpc"	"C:\\Users\\ekarni\\AppData\\Local\\nvim-data\\mason\\bin\\pylsp.CMD"	"stderr"	'2023-09-10 05:07:14,327 Jerusalem Summer Time - WARNING - pylsp.config.config - Failed to load hook pylsp_document_symbols: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pylsp\\config\\config.py", line 40, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_manager.py", line 457, in traced_hookexec
    return outcome.get_result()
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_result.py", line 76, in from_call
    result = func()
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_manager.py", line 454, in <lambda>
    lambda: oldcall(hook_name, hook_impls, caller_kwargs, firstresult)
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_callers.py", line 113, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pluggy\\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "c:\\users\\ekarni\\appdata\\local\\nvim-data\\mason\\packages\\python-lsp-server\\venv\\lib\\site-packages\\pylsp\\plugins\\symbols.py", line 94, in pylsp_document_symbols
    if _include_def(d) and Path(document.path) == Path(d.module_path):
  File "C:\\Users\\ekarni\\.pyenv\\pyenv-win\\versions\\3.9\\lib\\pathlib.py", line 1072, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\\Users\\ekarni\\.pyenv\\pyenv-win\\versions\\3.9\\lib\\pathlib.py", line 697, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\\Users\\ekarni\\.pyenv\\pyenv-win\\versions\\3.9\\lib\\pathlib.py", line 681, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType


```

I get this for every document.

**Comment by eyalk11** [comment]
OK, it because I specified root_folder like 'c:/users/' ... etc.
