### ISSUE TITLE
pylint plugin throws KeyError exception on pylint 3.0.0 prerelease

### ISSUE THREAD

**Issue by alexkyllo** [python-lsp/python-lsp-server#47]
When using python-lsp-server-1.0.1 with pylint-3.0.0, pylsp throws the following exception.

When I downgraded pylint to 2.9.1 (and simultaneously upgraded python-lsp-server to 1.1.0), the error went away, so I suspect it's probably due to breaking API changes in pylint 3.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pylsp/_utils.py", line 33, in run
    return func(*args, **kwargs)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pylsp/python_lsp.py", line 274, in lint
    flatten(self._hook('pylsp_lint', doc_uri, is_saved=is_saved))
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pylsp/python_lsp.py", line 155, in _hook
    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/hooks.py", line 281, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/manager.py", line 338, in traced_hookexec
    return outcome.get_result()
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/callers.py", line 52, in from_call
    result = func()
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/manager.py", line 336, in <lambda>
    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: _multicall(
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/callers.py", line 135, in _multicall
    return outcome.get_result()
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pluggy/callers.py", line 114, in _multicall
    res = hook_impl.function(*args)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pylsp/plugins/pylint_lint.py", line 182, in pylsp_lint
    return PylintLinter.lint(document, is_saved, flags=flags)
  File "/home/alex/.local/share/virtualenvs/Zurich-t2wvBLR8/lib/python3.8/site-packages/pylsp/plugins/pylint_lint.py", line 112, in lint
    line = diag['line'] - 1
KeyError: 'line'
```

**Comment by krassowski** [comment]
Thanks for the heads up. I am happy to look into it, but I could not find any changelog or list of breaking changes yet. By any chance, do you know if such a documentation exists? Also, it seems to me that pylint 3 is in alpha so I am not sure if we want to adopt already because it might be a moving target. It would be certainly good to start about compatibility when it reaches beta or RC.

**Comment by alexkyllo** [comment]
You're right, their changelog is still empty for 3.0, it looks like they're still very early and I probably shouldn't have been using that alpha release on PyPI. Definitely still a moving target. Feel free to close this if you want to wait until pylint 3 beta or RC to work on compat.
