### ISSUE TITLE
Method Not Found: textDocument/diagnostic

### ISSUE THREAD

**Issue by luozhouyang** [python-lsp/python-lsp-server#542]
Does python-lsp-server support `textDocument/diagnostic` method?
When I request a `textDocument/diagnostic` for a document, the server response error:
```bash
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/debug-agent/lib/python3.10/site-packages/pylsp_jsonrpc/endpoint.py", line 117, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/debug-agent/lib/python3.10/site-packages/pylsp_jsonrpc/endpoint.py", line 195, in _handle_request
    raise JsonRpcMethodNotFound.of(method) from e
pylsp_jsonrpc.exceptions.JsonRpcMethodNotFound: Method Not Found: textDocument/diagnostic
```

**Comment by nsikandar16** [comment]
is there any update on this issue?
