### ISSUE TITLE
Server not respecting flake8 ignores

### ISSUE THREAD

**Issue by vikigenius** [python-lsp/python-lsp-server#72]
So here is the flake8 section in my setup.cfg:

```
[flake8]
# Base flake8 configuration:
# https://flake8.pycqa.org/en/latest/user/configuration.html
format = wemake
show-source = True
statistics = False
doctests = True

# darglint configuration:
# https://github.com/terrencepreilly/darglint
strictness = long
docstring-style = numpy

# Plugins:
max-complexity = 6
max-line-length = 100

# wemake-python-styleguide settings:
i-control-code = False

# Disable some pydocstyle checks:
# Exclude some pydoctest checks globally:
ignore = D100, D104, D106, D401, W504, X100, RST303, RST304, DAR103, DAR203

# Excluding some directories:
exclude =
  .git
  __pycache__
  .venv
  .eggs
  *.egg

# Ignoring some errors in some files:
per-file-ignores =
  # Enable `assert` keyword and magic numbers for tests:
  tests/*.py: S101, WPS226, WPS432
  # __init__.py files are allowed to have unused imports and lines-too-long
  */__init__.py: F401, E121, WPS410

```

As given in the https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md I have correctly set the configuration sources to flake8. And also enabled the flake8 plugin.

But I am still getting the D100 error.

**Comment by vikigenius** [comment]
Also, maybe related but I am getting the following errors in the lsp-logs.

```
2021-08-21 03:09:34,532 EDT - ERROR - pylsp.plugins.flake8_lint - Error while running flake8 'WARNING:flake8.checker:The --jobs option is not compatible with supplying input using - . Ignoring --jobs arguments.
Traceback (most recent call last):
  File "/home/void/Projects/Python/redcloud/.venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/checker.py", line 323, in run
    self.run_serial()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/checker.py", line 307, in run_serial
    checker.run_checks()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8_plugin_utils/plugin.py", line 75, in run
    self._load_file()
  File "/home/void/Projects/Python/redcloud/.venv/lib/python3.9/site-packages/flake8_plugin_utils/plugin.py", line 87, in _load_file
    with open(self._filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'stdin'
'
```

**Comment by vikigenius** [comment]
Upon further debugging it seems like the warning is reported by pydocstyle not flake8. Disabling the pydocstyle plugin causes the warning to go away.

But there is another issue, the flake8 plugin doesn't actually work. It still shows the above error message. I am closing this issue and opening a new one to reflect this.
